### ISSUE TITLE
autoload会不停的加载

### ISSUE THREAD

**Issue by fengsx** [hefangshi/fis-postpackager-autoload#13]
更新之后，所有文件引入都会死循环加载
不停的读取

**Comment by hefangshi** [comment]
啥？ autoload都好久没更新了，能说说你的情况么？

**Comment by fengsx** [comment]
22天前更新的那个有问题

我今天重装了系统，重装了fis autoload simple之类的东东
用-w 监听死活不起作用。
不停地加载
![1](https://cloud.githubusercontent.com/assets/7709602/7879636/c656f3a6-0624-11e5-97f0-6b5a0b6ff481.jpg)
![qq 20150529170417](https://cloud.githubusercontent.com/assets/7709602/7879652/e6ef71c4-0624-11e5-9f8b-5125df600f64.jpg)

**Comment by hefangshi** [comment]
22天前的更新并没有发布

https://www.npmjs.com/package/fis-postpackager-autoload

上次发布已经是2个月以前了，你的问题应该是别的原因导致的。你不妨尝试逐版本回退FIS看看，或者方便的话把代码发一份到我的邮箱

hefangshi@gmai.com
