### ISSUE TITLE
pkg文件夹能否自定义位置？

### ISSUE THREAD

**Issue by fengsx** [hefangshi/fis-postpackager-autoload#6]
文档好少啊。。源码看的云里雾里

**Comment by hefangshi** [comment]
autoload插件不处理pkg路径问题，我想你问的可能是simple插件的自动打包功能的产出路径吧

https://github.com/hefangshi/fis-postpackager-simple#output

**Comment by fengsx** [comment]
嗯。。。其实我说的是ResourceMap的产出路径。。不是默认为pkg/page_map_XXX么。。我想问，我的配置咋不生效啊

fis.config.set('settings.postpackager.simple.output', 'aidebole/web/auto_combine_${index}');
