### ISSUE TITLE
pkg/page_map_这种目录格式是否固定？

### ISSUE THREAD

**Issue by fengsx** [hefangshi/fis-postpackager-autoload#7]
就是说，resourcemap是否在pkg/page_map_XXX这个默认目录下，不能自定义？

199行源码是：var subpath = 'pkg/page_map_${index}.js'.replace('${index}', asyncCount);

**Comment by hefangshi** [comment]
这里在autoload处是固定的，不过你可以通过roadmap.path配置去调整

```javascript
fis.config.get('roadmap.path').unshift({
    reg: /pkg\/page_map_(d+)\.js/,
    release: 'somewhereelse/$1.js'
});
```

不过更推荐的做法是

```
fis.config.set('settings.postpackager.autoload.useInlineMap', true);
```

直接将resourcemap内嵌入页面，可以减少一次请求

**Comment by fengsx** [comment]
怒赞！
刚学FIS。感觉你们要是有部完整的大文档就好了！！
感谢感谢，解决了我的大问题了。。。哈哈
