### ISSUE TITLE
页面最最终生成时，依赖的注释能否被清除

### ISSUE THREAD

**Issue by fengsx** [hefangshi/fis-postpackager-autoload#9]
rt
我打包完了。。。发现那些注释还在。想删除，咋弄啊？》

**Comment by hefangshi** [comment]
autoload的注释是会被清除的，不过你的情况是不是引入了一个相同的资源两次，导致第二个注释没被消除。

**Comment by fengsx** [comment]
配置是这样的
fis.config.set('modules.postpackager', 'autoload');
fis.config.set('modules.postpackager', 'autoload, simple');
fis.config.set('settings.postpackager.simple.autoCombine', true);
fis.config.set('settings.postpackager.simple.autoReflow', true); 
fis.config.set('roadmap.domain', '127.0.0.1:8080');
fis.config.set('roadmap.path', [
    {
        reg : /^\/views\/_views\/(.*\.tpl)/i,
        release : '/views/$1'
    },   
    {
        reg : /^\/aidebole\/web\/_web\/(.*)/i,
        release : '/aidebole/web/$1'
    }
]);

fis.config.merge({
    project : { 
        include : ['/aidebole/web/_web/**', 'views/_views/**']  
    }
});


引入大概是这样


结果最后没有被清除
也没有引用两次啊

**Comment by hefangshi** [comment]
编译没有清除的结果发来看看

**Comment by fengsx** [comment]
<link rel="stylesheet" type="text/css" href="http://test.yunsupport.com/aidebole/web/common/css/normalize.css">
<link rel="stylesheet" type="text/css" href="http://test.yunsupport.com/aidebole/web/common/css/common.css">
<link rel="stylesheet" type="text/css" href="http://test.yunsupport.com/aidebole/web/common/util/header/default/header.css">
<link rel="stylesheet" type="text/css" href="http://test.yunsupport.com/aidebole/web/common/util/pager/pager.css">
<link rel="stylesheet" type="text/css" href="http://test.yunsupport.com/aidebole/web/search/index.css">
<link rel="stylesheet" type="text/css" href="http://test.yunsupport.com/aidebole/web/common/util/footer/common/subfooter.css">

**Comment by fengsx** [comment]
![1](https://cloud.githubusercontent.com/assets/7709602/5724593/9f5f8b30-9b87-11e4-8f31-8ede0823265a.jpg)

**Comment by hefangshi** [comment]
这个require不是autoload引入的，属于FIS的资源声明注释，所以不会去除，你希望去除的话，可以考虑用插件做一下压缩

https://github.com/fouber/fis-optimizer-html-minifier
